<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NHPVION" failures="1" tests="7" name="TestNG.softassertionhardassertion" time="0.045" errors="0" timestamp="2023-06-14T12:54:26 PKT" skipped="5">
  <testcase classname="TestNG.softassertionhardassertion" name="test" time="0.003">
    <failure message="The following asserts failed:
	THis got failed expected [false] but found [true],
	THis got failed expected [false] but found [true],
	THis got failed expected [false] but found [true],
	THis got failed expected [false] but found [true],
	THis got failed expected [false] but found [true],
	THis got failed expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
THis got failed expected [false] but found [true],
THis got failed expected [false] but found [true],
THis got failed expected [false] but found [true],
THis got failed expected [false] but found [true],
THis got failed expected [false] but found [true],
THis got failed expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at TestNG.softassertionhardassertion.test(softassertionhardassertion.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test -->
  <testcase classname="TestNG.softassertionhardassertion" name="test" time="0.030">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="TestNG.softassertionhardassertion" name="test" time="0.002">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="TestNG.softassertionhardassertion" name="test" time="0.002">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="TestNG.softassertionhardassertion" name="test" time="0.002">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="TestNG.softassertionhardassertion" name="test" time="0.004">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="TestNG.softassertionhardassertion" name="test2" time="0.002"/>
</testsuite> <!-- TestNG.softassertionhardassertion -->
